### ISSUE TITLE
Memory Error In API Call

### ISSUE THREAD

**Issue by vsevolodnedora** [open-meteo/open-meteo#1041]
Reproducible Error when Calling history API as follows:

from datetime import datetime, timedelta
import pandas as pd
import openmeteo_requests
import requests_cache
from retry_requests import retry

cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

params = {
    "latitude": 52.6506,
    "longitude": 13.6866,
    "start_date": (pd.Timestamp( datetime.today().date(), tz='UTC' ) - timedelta(days=10)).strftime('%Y-%m-%d'),
    "end_date": (pd.Timestamp( datetime.today().date(), tz='UTC' )).strftime('%Y-%m-%d'),
    "hourly": 'temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m,wind_direction_10m',
}
url = "https://archive-api.open-meteo.com/v1/archive"
responses = openmeteo.weather_api(url, params=params)

response = responses[0]
hourly = response.Hourly()

Error:

Exception ignored in: <function Client.__del__ at 0x7532d03049d0>
Traceback (most recent call last):
  File "/home/vsevolod/.local/lib/python3.10/site-packages/openmeteo_requests/Client.py", line 58, in __del__
  File "/home/vsevolod/.local/lib/python3.10/site-packages/requests_cache/session.py", line 341, in close
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 797, in close
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 542, in close
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 222, in clear
  File "/usr/lib/python3/dist-packages/urllib3/_collections.py", line 95, in clear
TypeError: 'NoneType' object is not callable

**Comment by FastBack2499** [comment]
I guess this topic should help you. #1339

**Comment by patrick-zippenfenig** [comment]
Do I understand it correctly that this issue is triggered by `redis-py`?
