### ISSUE TITLE
Unable to run the app.py script and I get this error when I run that script. 

### ISSUE THREAD

**Issue by winash12** [open-meteo/open-meteo#1105]
`2024-11-10 11:30:59 INFO - get_cache_directory: Using /var/cache/pointwx/ as cache directory
Traceback (most recent call last):
  File "/home/winash12/point_wx-main/src/app.py", line 25, in <module>
    app = dash.Dash(
  File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 574, in __init__
    self.init_app()
  File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 653, in init_app
    self.enable_pages()
  File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 2189, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "/usr/local/lib/python3.9/dist-packages/dash/_pages.py", line 445, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/winash12/point_wx-main/src/pages/chatbot/layout.py", line 5, in <module>
    from .callbacks import *
  File "/home/winash12/point_wx-main/src/pages/chatbot/callbacks.py", line 11, in <module>
    client = OpenAI(api_key=OPENAI_KEY)
  File "/usr/local/lib/python3.9/dist-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable`

**Comment by patrick-zippenfenig** [comment]
Please report the issue in the corresponding repository: https://github.com/guidocioni/point_wx. Thanks!
