### ISSUE TITLE
Java SDK README okhttp3 example improvement

### ISSUE THREAD

**Issue by treinar** [open-meteo/open-meteo#616]
### Discussed in https://github.com/open-meteo/open-meteo/discussions/613

I propose adding just a small comment to this file: (https://github.com/open-meteo/sdk/tree/main/java):

```java
private byte[] responseIN = null;

// Step 1 : Request e.g.
// ----> Start suggested addition
// Please observe the parameter format=flatbuffers in mUrl, as the 
// WeatherApiResponse.getRootAsWeatherApiResponse((ByteBuffer) buffer.position(4));
// further down expects a flatbuffer and not Json - which is the default format returned from the API
// <--- End suggested addition
String mUrl = "https://api.open-meteo.com/v1/forecast?latitude=49.70808&longitude=8.08829&timezone=Europe/Berlin&minutely_15=temperature_2m,weathercode&format=flatbuffers";

okhttp3.Request request = new okhttp3.Request.Builder()
        .url(mUrl).method("GET", null)
        .build();

```

<div type='discussions-op-text'>

<sup>Originally posted by **treinar** January 19, 2024</sup>
Using your Java SDK example (https://github.com/open-meteo/sdk/tree/main/java) with okhttp3 as a starting point; I have created this synchronous call:

```java

// historicURL is currently= "https://archive-api.open-meteo.com/v1/archive?latitude=52.52&longitude=13.41&start_date=2024-01-01&end_date=2024-01-19&hourly=temperature_2m,relative_humidity_2m,rain,wind_speed_10m"
OkHttpClient client = new OkHttpClient();
        
        Request historicRequest = new Request.Builder()
                .url(historicURL).method("GET",null)
                .build();
        
        Call call = client.newCall(historicRequest);
        try
        {
            Response response = call.execute();
            if(response.isSuccessful())
            {
                //System.out.println(response.body().string());
                byte[] responseIN = response.body().bytes();
                ByteBuffer buffer = ByteBuffer.wrap(responseIN).order(ByteOrder.LITTLE_ENDIAN);
                WeatherApiResponse mApiResponse = WeatherApiResponse.getRootAsWeatherApiResponse((ByteBuffer) buffer.position(4));
                VariablesWithTime hourly = mApiResponse.hourly();
                VariableWithValues temperature2m = new VariablesSearch(hourly)
                        .variable(Variable.temperature)
                        .altitude(2) // Altitude e.g. temperature 2m
                        .first();
                System.out.println("Time= " + Instant.ofEpochSecond(hourly.time()).toString());
                System.out.println("TimeEnd= " + Instant.ofEpochSecond(hourly.timeEnd()).toString());
                for(int i = 0; i < temperature2m.valuesLength();i++)
                {
                    System.out.println(String.valueOf(temperature2m.values(i)));
                }
                buffer.clear();
            }
        }
        catch(IOException ex)
        {
            ex.printStackTrace();
        }
```
The code fails with:
```
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:693)
	at java.base/java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:406)
	at com.google.flatbuffers.Table.__reset(Table.java:301)
	at com.openmeteo.sdk.WeatherApiResponse.__init(WeatherApiResponse.java:29)
	at com.openmeteo.sdk.WeatherApiResponse.__assign(WeatherApiResponse.java:30)
	at com.openmeteo.sdk.WeatherApiResponse.getRootAsWeatherApiResponse(WeatherApiResponse.java:28)
	at com.openmeteo.sdk.WeatherApiResponse.getRootAsWeatherApiResponse(WeatherApiResponse.java:27)
```
, when running this line:

```java
WeatherApiResponse mApiResponse = WeatherApiResponse.getRootAsWeatherApiResponse((ByteBuffer) buffer.position(4));
```
When debug printing the response like this: `System.out.println(response.body().string()); `
...I get a valid Json string with weather data, so the request went fine

I am using your latest Maven release (1.4.0), and I see that the example using okhttp was added after that. 

If anybody would we willing to help me with this, I'd be very grateful. </div>

**Comment by patrick-zippenfenig** [comment]
Hi, thanks for the report!

Please feel free to open a PR as discussed in #613!

**Comment by treinar** [comment]
Done!

**Comment by patrick-zippenfenig** [comment]
Thanks! https://github.com/open-meteo/sdk/pull/59
